homeassistant:
  customize:
    input_boolean.house_occupied:
      hidden: true
    sensor.jakes_iphone_battery_level:
      hidden: true
    sensor.jakes_iphone_battery_state:
      hidden: true
    sensor.mandys_iphone_battery_level:
      hidden: true
    sensor.mandys_iphone_battery_state:
      hidden: true
    sensor.jakes_ipad_battery_level:
      hidden: true
    sensor.jakes_ipad_battery_state:
      hidden: true
      
device_tracker:
  - platform: linksys_smart
    host: !secret linksys
    interval_seconds: 15
    consider_home: 180
    track_new_devices: false

input_boolean:
  house_occupied:
    name: House Occupied
    initial: on
    
zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 150
    icon: mdi:castle

  - name: !secret abbyschool
    latitude: !secret abbyschool_latitude
    longitude: !secret abbyschool_longitude
    radius: 250
    icon: mdi:school
    
  - name: Work
    latitude: !secret mandywork_latitude
    longitude: !secret mandywork_longitude
    radius: 250
    icon: mdi:office-building
   
  - name: Work
    latitude: !secret jakework_latitude
    longitude: !secret jakework_longitude
    radius: 250