homeassistant:
  customize:
    binary_sensor.front_door:
      icon: mdi:door 
    binary_sensor.back_door:
      icon: mdi:door
    binary_sensor.kitchen_door:
      icon: mdi:door
    input_boolean.YOURSECRETDISARMBOOLEAN:
      hidden: true  
    input_boolean.fam_leaving:
      hidden: true      
      
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    trigger_time: 300
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 48
      delay_time: 30
    triggered:
      pending_time: 0
      
automation:
- id: activate_siren_actionable_notification
  alias: Activate Siren
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SIREN
  action:
    service: switch.turn_on
    entity_id: switch.alarm_siren
- id: disable_alarm_actionable_notification
  alias: Disable Alarm
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: DISABLEALARM
  action:
    service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret alarm_code
- id: enable_alarm_away_actionable_notification
  alias: Set Alarm Away
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: ARMAWAY
  action:
    service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret alarm_code
      
group:
  doors:
    name: Doors
    icon: mdi:door
    control: hidden
    entities:
     - binary_sensor.garage_door
     - binary_sensor.front_door
     - binary_sensor.back_door
     - binary_sensor.kitchen_door
    
  windows:
    name: Windows
    icon: mdi:window-closed
    control: hidden
    entities:
     - binary_sensor.bedroom_windows
     - binary_sensor.bathroom_window
     - binary_sensor.office_windows
     - binary_sensor.living_windows
     - binary_sensor.kitchen_windows
     - binary_sensor.laundry_window
     - binary_sensor.upstairs_windows  

input_boolean:
## Alexa Passprase Triggers to Arm_Away/Disarm System
  YOURSECRETDISARMBOOLEAN:
    name: SECRETDISARMBOOLEAN
    initial: off
  fam_leaving:
    name: Family Leaving
    initial: off
    
ios:
  push:
    categories:
      - name: alarm
        identifier: 'alarm'
        actions:
         - identifier: 'SIREN'
           title: 'Activate Siren!!!'
           activationMode: 'background'
           authenticationRequired: no
           destructive: yes
           behavior: 'default' 
         - identifier: 'DISABLEALARM'
           title: 'Oops...Disable Alarm'
           activationMode: 'background'
           authenticationRequired: no
           destructive: yes
           behavior: 'default'  
      - name: armaway
        identifier: 'armaway'
        actions:
         - identifier: 'ARMAWAY'
           title: 'Set Alarm Away Mode'
           activationMode: 'background'
           authenticationRequired: no
           destructive: yes
           behavior: 'default'    
      - name: disablealarm
        identifier: 'disablealarm'
        actions:
         - identifier: 'DISABLEALARM'
           title: 'Disable Alarm'
           activationMode: 'background'
           authenticationRequired: no
           destructive: yes
           behavior: 'default' 
      
konnected:
  access_token: !secret konnected_token
  api_host: !secret konnected_apihost
  devices:
    - id: !secret konnected_alarm1
      binary_sensors:
      # This Door Sensor Operates Inversely In My Home
        - zone: 1
          type: door
          name: 'Front Door'
          inverse: true 
        - zone: 2
          type: door
          name: 'Back Door'
      # This Door Sensor Operates Inversely In My Home
        - zone: 3
          type: door
          name: 'Kitchen Door'
          inverse: true
        - zone: 4
          type: window
          name: 'Living Windows'
        - zone: 5
          type: window
          name: 'Bedroom Windows'
        - zone: 6
          type: window
          name: 'Kitchen Windows'
    - id: !secret konnected_alarm2
      binary_sensors:
        - zone: 1
          type: window
          name: 'Bathroom Window'
        - zone: 2
          type: window
          name: 'Office Windows'
        - zone: 3
          type: window
          name: 'Laundry Window'
        - zone: 4
          type: window
          name: 'Upstairs Windows'
